---
- hosts: git
  remote_user: root
  tasks:
  - name: Update apt cache
    sudo: yes
    apt: update_cache=yes

  - name: Install python packages
    sudo: yes
    apt: pkg={{ item }} state=present
    with_items:
      - vim
      - python-pycurl
      - python-mysqldb

  - name: Install make
    apt: name=make update_cache=yes state=latest
  - name: Install autoconf
    apt: name=autoconf update_cache=yes state=latest
  - name: Install automake
    apt: name=automake update_cache=yes state=latest
  - name: install gcc
    apt: pkg=gcc state=present
  - name: install mysql-client
    apt: pkg=mysql-client state=present
  - name: Install Postfix
    apt: pkg=postfix state=installed update_cache=true
    notify:
      - start postfix
  - name: Configre Postfix for use with openproject
    lineinfile:
      dest=/etc/postfix/main.cf
      line="{{ item.line }}"
    with_items:
      - { line: 'smtp_sasl_auth_enable = yes' }
      - { line: 'smtp_sasl_security_options = noanonymous' }
      - { line: 'smtp_use_tls = yes' }
      - { line: 'relayhost = [mail.panikknopf.de]' }
    notify:
      - restart postfix  
  - name: Install GitLab Repo
    apt_repository: repo='deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ xenial main' state=present
  - name: Install GitLab SRC Repo
    apt_repository: repo='deb-src https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ xenial main' state=present
  - apt_key: url="https://packages.gitlab.com/gitlab/gitlab-ce/gpgkey" state=present
  - apt: name=gitlab-ce state=latest install_recommends=yes force=yes
    handlers:
    - name: start postfix
      service: name=postfix state=started
    - name: restart postfix
      service: name=postfix state=restarted
